@php
    use Illuminate\Support\Str;
@endphp

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="{{ csrf_token() }}"/>
<meta name="theme-color" content="#673C90">


{{--Add og: metatag on Epicollect5 home page--}}
@if(Route::currentRouteName() === 'home')
    <meta property="og:title" content="@yield('title')"/>
    <meta property="og:description" content="@yield('description')"/>
    <meta property="og:type" content="website"/>
    <meta property="og:image" content="{{asset('images/epicollect-icon-og-256x256@2x.png')}}"/>
    <meta property="og:image:width" content="128"/>
    <meta property="og:image:height" content="128"/>

    {{--add twitter card metadata--}}
    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:site" content="@EpiCollect"/>
    <meta name="twitter:title" content="Epicollect5"/>
    <meta name="twitter:description" content="@yield('title')"/>
    <meta name="twitter:image" content="{{asset('images/epicollect-icon-og-256x256@2x.png')}}"/>
@endif

@if(Route::currentRouteName() === 'login')
    <meta name="robots" content="noindex">
@endif

@if(Route::currentRouteName() === 'forgot-show')
    <meta name="robots" content="noindex">
@endif

{{--Add og: metatag on single project home page--}}
@if(isset($requestAttributes->requestedProject))
    @if(Route::currentRouteName() === 'project-home')
        @include('meta.meta_project_home')
    @endif

    @if(Route::currentRouteName() === 'project-open')
        @include('meta.meta_project_open')
    @endif
@endif

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"/>
<link href='https://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
<link rel="manifest" href="{{ asset('/json/app-manifest.json') }}">
<title>{{ config('app.name') }} - @yield('title')</title>

@include('favicon')

<meta name="description" content="@yield('description')">
<link rel="stylesheet" type="text/css" href="{{ asset('css/vendor-site.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('css/site.css').'?'.config('app.release') }}">

<script src="{{asset('/js/vendor-site.js').'?'.config('app.release') }}"></script>
<script src="{{asset('/js/site.js').'?'.config('app.release') }}"></script>
<script>
    window.EC5 = window.EC5 || {};
    window.EC5.SITE_URL = '{{url('')}}';
</script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.10/cookieconsent.min.js">
</script>

<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
    {
    "@context" : "https://schema.org",
    "@type" : "MobileApplication",
    "name" : "Epicollect5: Mobile & Web Application for free and easy data collection.",
    "image" : "https://lh3.googleusercontent.com/-L5eHfwSk22o/AAAAAAAAAAI/AAAAAAAAABA/yFVSoZ9TcDo/photo.jpg?sz=298",
    "url" : "https://five.epicollect.net/",
    "author" : {
      "@type" : "Organization",
      "name" : "Oxford University Big Data Institute"
    },
    "datePublished" : "2017-01-01",
    "applicationCategory" : "Mobile & Web Application for free and easy data collection",
    "operatingSystem": "Android, iOS"
  }
</script>

@if(Route::currentRouteName() === 'login' || Route::currentRouteName() === 'profile')

    <meta name="appleid-signin-scope" content="name email">
    @if(Route::currentRouteName() === 'login')
        <meta name="appleid-signin-client-id" content="{{config('auth.apple.login_client_id')}}">
        <meta name="appleid-signin-redirect-uri" content="{{config('auth.apple.login_redirect_uri')}}">
    @endif
    @if(Route::currentRouteName() === 'profile')
        <meta name="appleid-signin-client-id" content="{{config('auth.apple.connect_client_id')}}">
        <meta name="appleid-signin-redirect-uri" content="{{config('auth.apple.connect_redirect_uri')}}">
    @endif
    <meta name="appleid-signin-nonce" content="{{$nonce}}">
@endif


<!-- End Cookie Consent plugin -->

{{--Add analytics only for production site--}}
@if(config('app.env') == 'production')
    <script defer data-domain="five.epicollect.net" src="https://analytics.cgps.dev/js/plausible.js"></script>
@endif

{{--Apple Sign in--}}
<script type="text/javascript"
        src="https://appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js"></script>

{{-- Share Links js--}}
@if(Str::is('*.epicollect.net', config('app.url')))
    <script type='text/javascript'
            src='//platform-api.sharethis.com/js/sharethis.js#property={{config('epicollect.setup.sharethis.property_id')}}&product=inline-share-buttons'
            async='async'>
    </script>
@else
    {{--    Not working on localhost but buttons are still displayed--}}
    <script type='text/javascript'
            src='//platform-api.sharethis.com/js/sharethis.js#property={{config('epicollect.setup.sharethis.property_id')}}&product=inline-share-buttons'
            async='async'>
    </script>
@endif
