<?php

namespace ec5\DTO;

use ec5\Libraries\Utilities\Arrays;
use ec5\Services\Mapping\ProjectMappingService;

/*
|--------------------------------------------------------------------------
| Project Mapping DTO
|--------------------------------------------------------------------------
| A DTO for the JSON Data Mapping
|
*/

class ProjectMappingDTO extends ProjectDTOBase
{
    public function init(array|string $data): void
    {
        // Older rows may contain more than one default mapping due to a bug.
        // Normalize on read so the UI and API see a single effective default
        // without rewriting the stored JSON.
        parent::init($data);
        $this->data = $this->normalizeDefaultMappings($this->data);
    }

    public function create(array $data): void
    {
        $this->data = $data;
    }

    public function updateProjectDetails(array $data)
    {
        //
    }

    public function getMapCount(): int
    {
        return count($this->data);
    }

    public function deleteMapping(int $mapIndex): void
    {
        // If we are deleting the default mapping, we must
        // set the auto generated as the new default
        if ($this->data[$mapIndex]['is_default']) {
            $this->data[0]['is_default'] = true;
        }
        unset($this->data[$mapIndex]);
    }

    // Get an array of all the map indexes
    public function getMapIndexes(): array
    {
        return array_keys($this->data);
    }

    public function setEC5AUTOMapping(array $mapping): void
    {
        $this->data[0] = $mapping;
    }

    public function createCustomMapping(array $payload): void
    {
        // Get the auto-generated map (always indexed 0)
        $autoGeneratedMap = $this->data[0];
        // Get the next available map number
        end($this->data);
        $nextAvailableMapIndex = key($this->data) + 1;
        $isDefault = $payload['is_default'] ?? false;

        $this->data[$nextAvailableMapIndex] = [
            'name' => $payload['name'],
            'is_default' => $isDefault,
            // Set the auto-generated map as the content of the new map
            'forms' => $autoGeneratedMap['forms'],
            'map_index' => $nextAvailableMapIndex
        ];

        // Set this as the default map if required
        if ($isDefault) {
            $this->setDefault($nextAvailableMapIndex);
        }
    }

    public function addImportedMapping(array $mapping): void
    {
        end($this->data);
        $nextAvailableMapIndex = key($this->data) + 1;

        $mapping['map_index'] = $nextAvailableMapIndex;
        $mapping['is_default'] = true;

        $this->data[$nextAvailableMapIndex] = $mapping;
        $this->setDefault($nextAvailableMapIndex);
    }

    public function setDefault(int $mapIndex): void
    {
        // Set all mappings as default false
        foreach ($this->data as $index => $mapping) {
            $this->data[$index]['is_default'] = false;
        }

        // Set the required mapping default to true
        $this->data[$mapIndex]['is_default'] = true;
    }

    public function renameMap(int $mapIndex, string $name): void
    {
        $this->data[$mapIndex]['name'] = $name;
    }

    public function updateMap(int $mapIndex, array $map): void
    {
        //preserve default mapping
        $map['is_default'] = $this->data[$mapIndex]['is_default'];
        $this->data[$mapIndex] = $map;
    }

    public function updateMappings(ProjectExtraDTO $projectExtra, ProjectMappingService $projectMappingService): void
    {
        // Recreate the EC5 AUTO mapping
        $mapping = $projectMappingService->createEC5AUTOMapping($projectExtra->getData());
        $this->setEC5AUTOMapping($mapping);

        // Then loop each map in $this->data and update
        foreach ($this->data as $mapIndex => $value) {
            if ($mapIndex == 0) {
                continue;
            }
            // Merge each map with the auto generated
            $this->data[$mapIndex] = Arrays::merge($this->data[0], $this->data[$mapIndex]);
        }
    }

    public function getLastMapIndex(): int
    {
        // Point to the last item in $this->data array
        end($this->data);
        return key($this->data);
    }

    public function getMap(int $mapIndex, string $formRef): array
    {
        return $this->data[$mapIndex]['forms'][$formRef] ?? [];
    }

    public function getDefaultMapIndex(): int
    {
        // Retrieve default map
        foreach ($this->data as $mapIndex => $mapping) {
            if ($this->data[$mapIndex]['is_default']) {
                return $mapIndex;
            }
        }
        // Otherwise, return auto map
        return 0;
    }

    public function getDefaultMapName(): string
    {
        // Retrieve default map name
        foreach ($this->data as $mapIndex => $mapping) {
            if ($this->data[$mapIndex]['is_default']) {
                return $mapping['name'];
            }
        }
        // Otherwise, return EC5 AUTO mapping
        return config('epicollect.mappings.default_mapping_name');
    }

    public function getMapDetails(int $mapIndex): array
    {
        // If a map index was not supplied, set the default
        if (!isset($this->data[$mapIndex])) {
            $mapIndex = $this->getDefaultMapIndex();
        }

        return [
            'map_name' => $this->data[$mapIndex]['name'],
            'map_index' => $mapIndex
        ];
    }

    private function normalizeDefaultMappings(array $data): array
    {
        $defaultMappings = [];

        foreach ($data as $mapIndex => $mapping) {
            //cache default mapping
            if (($mapping['is_default'] ?? false) === true) {
                $defaultMappings[] = $mapIndex;
            }
            $data[$mapIndex]['is_default'] = false;
        }

        //if only one mapping found, restore it as is
        if (count($defaultMappings) === 1) {
            $data[$defaultMappings[0]]['is_default'] = true;
            return $data;
        }

        if (count($defaultMappings) > 1) {
            // If both EC5 AUTO and a custom mapping are marked as default,
            // prefer the custom one and let the user correct it in the UI.
            foreach ($defaultMappings as $mapIndex) {
                if ($mapIndex !== 0) {
                    $data[$mapIndex]['is_default'] = true;
                    return $data;
                }
            }
        }

        if (isset($data[0])) {
            // Fall back to EC5 AUTO when no valid single default exists.
            $data[0]['is_default'] = true;
        }

        return $data;
    }
}
