<?php

return [
    'UNIT_TEST_RANDOM_EMAIL' => env('UNIT_TEST_RANDOM_EMAIL'),
    'SUPER_ADMIN_EMAIL' => env('SUPER_ADMIN_EMAIL'),
    'CREATOR_EMAIL' => env('CREATOR_EMAIL'),
    'MANAGER_EMAIL' => env('MANAGER_EMAIL'),
    'PASSWORDLESS_TOKEN_EXPIRES_IN' => env('PASSWORDLESS_TOKEN_EXPIRES_IN'),
    'BCRYPT_ROUNDS' => env('BCRYPT_ROUNDS')
];
