name: Generate Release Notes

on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*' # Triggers the workflow when a tag matching the version pattern is pushed (e.g., 11.1.1)

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract release notes from CHANGELOG.md
        id: changelog
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/} # Extract the tag (e.g., 11.1.1)
          echo "Extracting release notes for version: $TAG_VERSION"
          RELEASE_NOTES=$(awk -v version="$TAG_VERSION" '
          $0 ~ "^## \\[" version "\\]" {flag=1; next}
          $0 ~ "^## \\[" && flag {exit}
          flag {print}
          ' CHANGELOG.md)
          
          # Guard against missing or empty release notes
          if [ -z "$RELEASE_NOTES" ]; then
          echo "Error: No release notes found for version $TAG_VERSION" >&2
          exit 1
          fi
          
          # Write multi-line release notes to GitHub Actions output safely
          printf "release_notes<<EOF\n%s\nEOF\n" "$RELEASE_NOTES" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.release_notes }}
          draft: false
          prerelease: false
