name: Generate Release Notes

on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*' # Triggers the workflow when a tag matching the version pattern is pushed (e.g., 11.1.1)

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract release notes from CHANGELOG.md
        id: changelog
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/} # Extract the tag (e.g., 11.1.21)
          echo "Extracting release notes for version: $TAG_VERSION"

          # Extract release notes using awk based on the version in the changelog
          RELEASE_NOTES=$(awk -v version="$TAG_VERSION" '
          $0 ~ "^# " version {flag=1; next}  # Look for the version heading
          $0 ~ "^# " && flag {exit}         # Exit when the next heading is found
          flag {print}                       # Print the lines while flag is set
          ' CHANGELOG.md)

          # Guard against missing or empty release notes
          if [ -z "$RELEASE_NOTES" ]; then
            echo "Error: No release notes found for version $TAG_VERSION" >&2
            exit 1 
          fi
          
          # Escape multiline content for GitHub Actions output
          # Escape only percent signs (necessary for GitHub Actions output)
          RELEASE_NOTES="${RELEASE_NOTES//'%'/'%25'}"
          
          # Write to GitHub Actions output
          echo "release_notes=${RELEASE_NOTES}" >> $GITHUB_OUTPUT


      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.release_notes }}
          draft: false
          prerelease: false
